version: '3'

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

